<!DOCTYPE HTML>
<html>
<head>
	<title><?php echo TITLE; ?></title>
	<base href="<?php echo BASE; ?>">
	<link rel="stylesheet" href="css/pixelmural.css">
	<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="js/jgestures.min.js"></script>
	<script src="js/mural.js"></script>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
</head>
<body>

	<canvas id="mural"></canvas>

</body>
</html>