<!DOCTYPE HTML>
<html>
<head>
	<title><?php echo TITLE; ?></title>
	<base href="<?php echo BASE; ?>">
	<link rel="stylesheet" href="css/pixelmural.css">
	<link rel="icon" href="images/favicon.ico">
	<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="js/functions.js"></script>
	<script src="js/mural.js"></script>
	<script src="js/ga.js"></script>
	<meta charset="UTF-8">
	<meta name="description" content="<?php echo DESCRIPTION; ?>">
	<meta name="viewport" content="width=device-width">
</head>
<body>

	<canvas id="mural"></canvas>

	<img id="loading" src="images/loading.gif" title="Loading..." alt="Loading...">

</body>
</html>