<!DOCTYPE HTML>
<html>
<head>
	<title><?php echo TITLE; ?></title>
	<base href="<?php echo BASE; ?>">
	<link rel="stylesheet" href="css/pixelmural.css">
	<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="js/functions.js"></script>
	<script src="js/mural.js"></script>
	<script src="js/touch.js"></script>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
</head>
<body>

	<div id="header">

		<div id="facebook-menu" class="menu">
			<button id="facebook-share-button" title="Share on Facebook"><img src="images/facebook-share.png" alt="Share"></button>
			<button id="facebook-login-button" title="Log in with Facebook"><img src="images/facebook-login.png" alt="Login"></button>
			<button id="facebook-logout-button" title="Log out from Facebook"><img src="images/facebook-logout.png" alt="Logout"></button>
			<img id="profile-picture" src="images/anon.png">
		</div>

	</div>

	<canvas id="mural"></canvas>

	<img id="loading" src="images/loading.gif" title="Loading..." alt="Loading...">

</body>
</html>